/* =========================================================
   RUNTIME — clock, playback, scrubbing, kinetic typography, builders.
   Loaded by every beat page after defs.js (and after beats.js, which the
   build script generates with the shot table for the readout).

   Every animation is a CSS animation that stays PAUSED until playback
   (body.playing), or a GSAP timeline scrubbed by M.seek(). One clock drives
   both, so play / scrub / render are always in agreement.
   ========================================================= */

const CFG = {
  offset:+(document.body.dataset.offset||0),
  dur:+(document.body.dataset.dur||10),
  beat:+(document.body.dataset.beat||0)
};
const PART = +(document.body.dataset.part||1);
/* beats.js (generated by build) sets window.PROJECT = {title, parts:{1:{total, beats:[{n,t,name}]}}} */
const _P = (window.PROJECT && window.PROJECT.parts && window.PROJECT.parts[PART]) || {};
const BEATS = _P.beats || [];
const TOTALOF = _P.total || CFG.dur;
const PARTLABEL = "PART " + PART;

const $  = s=>document.querySelector(s);
const $$ = s=>[...document.querySelectorAll(s)];
const stage=$("#stage"), fill=$("#fill"), tc=$("#tc"), nowBeat=$("#nowBeat");

/* =========================================================
   EL — reusable motion-design utilities
   ========================================================= */
const EL = {

  /* seeded RNG so procedural art is identical every render */
  rng(seed){
    let a = seed >>> 0;
    return function(){
      a |= 0; a = a + 0x6D2B79F5 | 0;
      let t = Math.imul(a ^ a>>>15, 1 | a);
      t = t + Math.imul(t ^ t>>>7, 61 | t) ^ t;
      return ((t ^ t>>>14) >>> 0) / 4294967296;
    };
  },

  /* smooth periodic value noise — the basis of every organic edge here */
  noise(seed, n=10){
    const r = EL.rng(seed), p = Array.from({length:n}, ()=>r());
    return t => {
      const x = t*(n-1), i = Math.floor(x), f = x-i;
      const a = p[((i%n)+n)%n], b = p[((i+1)%n+n)%n];
      return a + (b-a)*(f*f*(3-2*f));
    };
  },

  /* an organic ridge line across 1080 units — mountains, ice, dunes */
  ridge(seed, baseY, amp, w=1080, steps=8, bias=0){
    const n = EL.noise(seed, steps+3), pts = [];
    for(let i=0;i<=steps;i++) pts.push(baseY + (n(i/steps)-.5)*amp + bias);
    let d = `M0 ${pts[0].toFixed(1)}`;
    for(let i=1;i<=steps;i++){
      const x0 = (i-1)*(w/steps), x1 = i*(w/steps);
      const y0 = pts[i-1], y1 = pts[i];
      d += ` C ${(x0+(x1-x0)*.34).toFixed(1)} ${y0.toFixed(1)}`
        +  ` ${(x0+(x1-x0)*.66).toFixed(1)} ${y1.toFixed(1)}`
        +  ` ${x1.toFixed(1)} ${y1.toFixed(1)}`;
    }
    return d;
  },

  /* A layered depth plane. The ridge line is the TOP edge and the plane
     fills DOWNWARD to the bottom of frame — so nearer planes (lower baseY)
     occlude the ones behind them and you actually see the ridgeline.
     Filling upward to a `top` value hides the noise behind a hard
     horizontal edge and every plane collapses into a flat band. */
  plane(seed, baseY, amp, bottom=1920, w=1080, steps=8, sharp=0){
    const n = EL.noise(seed, steps+3), pts = [];
    for(let i=0;i<=steps;i++){
      let v = (n(i/steps)-.5)*amp;
      if(sharp) v = Math.sign(v) * Math.pow(Math.abs(v)/amp*2, sharp) * (amp/2);
      pts.push(baseY + v);
    }
    let d = `M0 ${pts[0].toFixed(1)}`;
    for(let i=1;i<=steps;i++){
      const x0=(i-1)*(w/steps), x1=i*(w/steps), y0=pts[i-1], y1=pts[i];
      const pull = i===steps ? 0 : 0;   // keep curve tension constant
      d += ` C ${(x0+(x1-x0)*.30).toFixed(1)} ${y0.toFixed(1)}`
        +  ` ${(x0+(x1-x0)*.70-pull).toFixed(1)} ${y1.toFixed(1)}`
        +  ` ${x1.toFixed(1)} ${y1.toFixed(1)}`;
    }
    return d + ` L${w} ${bottom} L0 ${bottom} Z`;
  },

  /* a ridge that ramps across the frame — diagonals read as composed,
     horizontal ridges read as wallpaper */
  ridgeRamp(seed, x0, y0, x1, y1, steps=8, amp=100){
    const n = EL.noise(seed, steps+3), pts = [];
    for(let i=0;i<=steps;i++){
      const t = i/steps;
      pts.push([x0+(x1-x0)*t, y0+(y1-y0)*t + (n(t)-.5)*amp]);
    }
    let d = `M${pts[0][0].toFixed(1)} ${pts[0][1].toFixed(1)}`;
    for(let i=1;i<=steps;i++){
      const p = pts[i-1], c = pts[i];
      d += ` C ${(p[0]+(c[0]-p[0])*.34).toFixed(1)} ${p[1].toFixed(1)}`
        +  ` ${(p[0]+(c[0]-p[0])*.66).toFixed(1)} ${c[1].toFixed(1)}`
        +  ` ${c[0].toFixed(1)} ${c[1].toFixed(1)}`;
    }
    return d;
  },

  /* moisture beads: body + specular dot + contact shadow.
     This is what stops a drawn mushroom looking like clip art. */
  bead(x, y, r){
    return `<g>
      <ellipse cx="${(x+r*.28).toFixed(1)}" cy="${(y+r*.42).toFixed(1)}"
               rx="${(r*1.05).toFixed(1)}" ry="${(r*.72).toFixed(1)}"
               fill="#1A1208" opacity=".26"/>
      <circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${r.toFixed(1)}"
              fill="url(#beadG)"/>
      <circle cx="${(x-r*.30).toFixed(1)}" cy="${(y-r*.36).toFixed(1)}"
              r="${(r*.22).toFixed(1)}" fill="#FFFFFF" opacity=".55"/>
      <circle cx="${(x+r*.34).toFixed(1)}" cy="${(y+r*.30).toFixed(1)}"
              r="${(r*.09).toFixed(1)}" fill="#CFE6F7" opacity=".30"/>
    </g>`;
  },

  /* set animation via LONGSHAND so the play-state gate survives.
     NEVER use the `animation:` shorthand, here or in inline styles —
     it resets animation-play-state to running, which makes the whole
     preview animate before you press play. */
  anim(el, name, delay, dur=1, ease="var(--e-expo)", extra={}){
    if(!el) return el;
    el.classList.add("kf");
    el.style.animationName = name;
    el.style.animationDuration = dur + "s";
    el.style.animationTimingFunction = ease;
    el.style.animationDelay = delay + "s";
    for(const k in extra) el.style[k] = extra[k];
    return el;
  },

  /* Several animations on ONE element. EL.anim() called twice on the same
     element overwrites animationName and silently drops the first.

     PER-ENTRY FILL MATTERS. With fill-mode:both, an animation shows its 0%
     block during its delay phase, and the LAST entry in the list wins every
     property. So stacking `slam` (0% opacity:0) then `f1` (0% opacity:1)
     makes the element visible from t=0, because f1's backwards fill wins.

     For "hidden until A, visible A..B, gone after B", give the EXIT entry
     fill:"forwards" — then it contributes nothing before B and the entrance's
     backwards fill correctly holds it hidden. */
  animMulti(el, list){
    if(!el) return el;
    el.classList.add("kf");
    el.style.animationName           = list.map(a=>a.name).join(",");
    el.style.animationDuration       = list.map(a=>a.dur+"s").join(",");
    el.style.animationTimingFunction = list.map(a=>a.ease||"var(--e-expo)").join(",");
    el.style.animationDelay          = list.map(a=>a.delay+"s").join(",");
    el.style.animationFillMode       = list.map(a=>a.fill||"both").join(",");
    const it = list.map(a=>a.iter||1).join(",");
    if (it !== "1,1") el.style.animationIterationCount = it;
    const dirs = list.map(a=>a.dir||"normal").join(",");
    if (!/^normal(,normal)*$/.test(dirs)) el.style.animationDirection = dirs;
    return el;
  },

  /* infinite ambient loops — drift, breath, shimmer */
  loop(el, name, dur, ease="var(--e-circ-io)", alt=true){
    if(!el) return el;
    el.classList.add("kf");
    el.style.animationName = name;
    el.style.animationDuration = dur + "s";
    el.style.animationTimingFunction = ease;
    el.style.animationIterationCount = "infinite";
    el.style.animationDirection = alt ? "alternate" : "normal";
    return el;
  },

  /* KINETIC TYPOGRAPHY — the biggest single upgrade over a block fade.
     Chars MUST be inline-block: transforms do not apply to
     non-replaced inline elements, so a plain <span> would silently
     do nothing. Wrap the target in .kline for the masked rise. */
  kinetic(target, {stagger=0.024, dur=.72, delay=0, ease="var(--e-expo)",
                  name="fadeUp"}={}){
    if(!target) return target;
    /* Walk the real nodes, not textContent. textContent throws away every <br>,
       which runs "Line one<br>line two" together into one line that then
       breaks mid-word. Each WORD is a
       nowrap box holding its animated characters, so a line can only ever
       break between words. */
    const nodes = [...target.childNodes];
    target.textContent = "";
    target.style.whiteSpace = "normal";
    let i = 0, out = target;
    const addText = txt => {
      txt.split(/(\s+)/).forEach(part=>{
        if(!part) return;
        if(/^\s+$/.test(part)){ out.appendChild(document.createTextNode(" ")); return; }
        const w = document.createElement("span");
        w.style.cssText = "display:inline-block;white-space:nowrap";
        for(const ch of part){
          const s = document.createElement("span");
          s.textContent = ch;
          s.style.display = "inline-block";
          s.style.willChange = "transform,opacity";
          EL.anim(s, name, delay + i*stagger, dur, ease);
          w.appendChild(s); i++;
        }
        out.appendChild(w);
      });
    };
    /* inline elements (a coloured <span>) are kept as shallow clones so their
       styling survives the split */
    const walk = n => {
      if(n.nodeType === 3) addText(n.textContent);
      else if(n.nodeName === "BR") out.appendChild(document.createElement("br"));
      else { const keep = out, c = n.cloneNode(false); out.appendChild(c); out = c;
             n.childNodes.forEach(walk); out = keep; }
    };
    nodes.forEach(walk);
    return target;
  },

  /* WORD-AWARE kinetic type. USE THIS FOR BODY COPY.
     Each WORD is an inline-block animated as a unit, so line breaking only
     happens at word boundaries. <br> in the source is preserved — the old
     textContent version silently deleted them ("say:I'll", "thinkbefore"). */
  kineticWords(target, {stagger=.030, dur=.70, delay=0, ease="var(--e-expo)",
                       name="riseMask", joiner=" "}={}){
    if(!target) return target;
    const nodes = [...target.childNodes];
    target.textContent = "";
    target.style.whiteSpace = "normal";
    let i = 0, pendingSpace = false, out = target, started = false;
    const addText = txt => {
      txt.split(/(\s+)/).forEach(part=>{
        if(!part) return;
        if(/^\s+$/.test(part)){ pendingSpace = true; return; }
        if(pendingSpace && started) out.appendChild(document.createTextNode(joiner));
        started = true;
        pendingSpace = false;
        const span = document.createElement("span");
        span.textContent = part;
        span.style.display = "inline-block";
        span.style.willChange = "transform,opacity";
        span.style.whiteSpace = "pre";
        EL.anim(span, name, delay + i*stagger, dur, ease);
        out.appendChild(span); i++;
      });
    };
    const walk = n => {
      if(n.nodeType === 3) addText(n.textContent);
      else if(n.nodeName === "BR"){ out.appendChild(document.createElement("br")); pendingSpace = false; started = false; }
      else { const keep = out, c = n.cloneNode(false); out.appendChild(c); out = c;
             n.childNodes.forEach(walk); out = keep; }
    };
    nodes.forEach(walk);
    return target;
  },

  /* same, but line-masked — characters rise out from behind a hard edge.
     Use on the big display type; use kinetic() on body copy. */
  kineticLines(target, opts={}){
    EL.kinetic(target, opts);
    target.classList.add("kline");
    return target;
  },

  /* --- builders -------------------------------------------
     Each takes explicit timings. Called by the beat that owns them,
     never auto-called here: learned that auto-calling builders
     silently double-builds anything a beat also constructs itself. */

  /* the Q quote card — the most reused element in the film.
     Geometry must be IDENTICAL everywhere or it stops reading as one
     physical artifact and becomes decoration. */
  qcard(mount, {text, attr, cls="", pop=0, dur=.5}={}){
    const w = document.createElement("div");
    w.className = "qcard " + cls;
    w.innerHTML =
      `<div class="qtext" id="qt">${text}</div>` +
      (attr ? `<div class="qattr">${attr}</div>` : "");
    EL.anim(w, "qIn", pop, dur, "var(--e-expo)");
    mount.appendChild(w);
    return w;
  },

  /* WORD SYNC. After kineticWords(), re-time each word to the moment it is
     spoken. `times` are local seconds from the real VO (vosync_p1.py). If the
     on-screen spelling has a different word count from the spoken one ("4pm"
     vs "four P.M."), the times are resampled linearly onto the visible words. */
  syncWords(target, times, lead=.06){
    if(!target || !times || !times.length) return target;
    const spans = [...target.querySelectorAll("span")].filter(s=>s.style.willChange);
    const n = spans.length, m = times.length;
    spans.forEach((s,i)=>{
      const x = n===1 ? 0 : i*(m-1)/(n-1), a = Math.floor(x), f = x-a;
      const t = times[a] + ((times[Math.min(a+1,m-1)] - times[a]) * f);
      s.style.animationDelay = Math.max(0, t-lead).toFixed(3) + "s";
    });
    return target;
  },

  /* PAGED QUOTE CARDS. A long quote is split into pages so no frame carries
     more than ~25 words (series rule). Each page is the SAME card geometry at
     the same top, so it reads as one artifact turning over, not new cards.
     pages: [{text, at, end, cls}] — `at` is when its first word is spoken,
     `end` when the page leaves (omit on the last page: it holds to `hold`).
     Words are paced across the spoken span so type lands WITH the voice
     rather than racing ahead of it. */
  pages(mount, pages, {attr="", top=360, hold=null, rate=2.5, holdGaps=false}={}){
    const cards = [];
    let freeAt = 0;   /* when the previous page has fully left: pages never overlap */
    pages.forEach((p,i)=>{
      const pop = Math.max(0, p.at-(holdGaps ? .2 : .35), freeAt);
      const c = EL.qcard(mount, {text:p.text, attr, cls:p.cls||"", pop, dur:.45});
      c.style.top = (p.top || top) + "px";
      const qt = c.querySelector("#qt");
      const n = qt.textContent.trim().split(/\s+/).length;
      const span = p.span || n / rate;
      const stagger = Math.max(.025, Math.min(.30, span / Math.max(1,n)));
      EL.kineticWords(qt, {name:"wordIn", stagger, dur:.42, delay:p.at});
      if (p.times) EL.syncWords(qt, p.times);
      const a = c.querySelector(".qattr");
      if (a) EL.anim(a, "quietIn", Math.max(0,p.at-.1), .5, "var(--e-soft)");
      let out = p.end != null ? p.end : hold;
      /* holdGaps: in a long pause the page stays up until the next one is
         about to arrive, instead of leaving an empty frame */
      if (holdGaps && p.end != null && pages[i+1]) out = Math.max(p.end, pages[i+1].at - .62);
      const list = [{name:"qIn", dur:.45, delay:pop, ease:"var(--e-expo)"}];
      if (out != null) list.push({name:"cardOut", dur:.24, delay:out, ease:"linear", fill:"forwards"});
      if (out != null) freeAt = out + .26;
      EL.animMulti(c, list);
      cards.push(c);
    });
    return cards;
  },

  /* NARRATOR CARD. Register N: no card chrome, no amber, a mono kicker and a
     display line set on the cold plate. Arrives hard (nIn), words paced to VO. */
  ncard(mount, {kicker="", text="", at=.2, top=760, size=78, end=null, rate=2.6, color="var(--ink)", times=null}={}){
    const w = document.createElement("div");
    w.className = "layer";
    w.innerHTML =
      (kicker ? `<div class="kicker" style="position:absolute;left:110px;top:${top-96}px;border-left:6px solid var(--n);padding-left:22px;line-height:44px">${kicker}</div>` : "") +
      `<div class="n-head" style="position:absolute;left:110px;top:${top}px;width:860px;font-size:${size}px;color:${color}">${text}</div>`;
    mount.appendChild(w);
    const head = w.querySelector(".n-head");
    const n = head.textContent.trim().split(/\s+/).length;
    EL.kineticWords(head, {name:"wordIn", stagger:Math.max(.03, Math.min(.3, n/rate/n)), dur:.42, delay:at});
    if (times) EL.syncWords(head, times);
    const k = w.querySelector(".kicker");
    if (k) EL.anim(k, "nIn", Math.max(0,at-.15), .12, "linear");
    if (end != null) EL.animMulti(w, [{name:"nIn", dur:.01, delay:0, ease:"linear"},
                                      {name:"cardOut", dur:.35, delay:end, ease:"linear", fill:"forwards"}]);
    return w;
  },

  /* the N cold-in. Facts arrive; they do not dissolve. */
  nwipe(mount, {pop=0, dur=.34}={}){
    const w = document.createElement("div");
    w.className = "layer";
    w.style.cssText = "position:absolute;inset:0;background:var(--deep)";
    EL.anim(w, "nWipe", pop, dur, "linear");
    mount.appendChild(w);
    return w;
  },

  /* the quote card leaving. Exits need fill:"forwards" or the
     backwards fill shows the element before its own delay. */
  qcardOut(card, {at, dur=.5}={}){
    if(!card) return;
    EL.animMulti(card, [
      {name:"cardOut", dur, delay:at, ease:"linear", fill:"forwards"}
    ]);
  },

  /* the amber left rule drawing itself — the "this is his voice" marker */
  qrule(card, {at=0, dur=.5}={}){
    const r = card && card.querySelector("::before");
    return r; /* border-left is CSS; the wipe is on the whole card */
  },

  /* the clock in shot 3. steps() so it TICKS rather than sweeps —
     a sweeping second hand reads as a stock transition. */
  clock(cx=540, cy=520, r=150){
    const ticks = Array.from({length:60},(_,i)=>{
      const a = (i/60)*Math.PI*2 - Math.PI/2, big = i%5===0;
      return `<line x1="${(cx+Math.cos(a)*(r-14)).toFixed(1)}" y1="${(cy+Math.sin(a)*(r-14)).toFixed(1)}"
                    x2="${(cx+Math.cos(a)*(r-(big?36:24))).toFixed(1)}" y2="${(cy+Math.sin(a)*(r-(big?36:24))).toFixed(1)}"
                    stroke="#3A2614" opacity="${big?0.9:0.45}" stroke-width="${big?4:1.6}"/>`;
    }).join("");
    /* a real wall clock: rim, warm face lit from the window, fixed hour and
       minute hands, and the one thing that moves — the second hand. */
    return `<g>
      <circle cx="${cx+10}" cy="${cy+14}" r="${r+6}" fill="#000" opacity=".45" filter="url(#soft18)"/>
      <circle cx="${cx}" cy="${cy}" r="${r+10}" fill="#2A1A0C"/>
      <circle cx="${cx}" cy="${cy}" r="${r+10}" fill="none" stroke="#C99050" stroke-width="2.5" opacity=".55"/>
      <circle cx="${cx}" cy="${cy}" r="${r}" fill="#D9B57E"/>
      <circle cx="${cx}" cy="${cy}" r="${r}" fill="url(#keyLight)"/>
      <circle cx="${cx-r*.25}" cy="${cy-r*.3}" r="${r*.75}" fill="#FFF3DD" opacity=".18" filter="url(#soft18)"/>
      ${ticks}
      <line x1="${cx}" y1="${cy}" x2="${(cx+r*.42).toFixed(1)}" y2="${(cy+r*.22).toFixed(1)}" stroke="#2A1A0C" stroke-width="9" stroke-linecap="round"/>
      <line x1="${cx}" y1="${cy}" x2="${(cx-r*.22).toFixed(1)}" y2="${(cy-r*.68).toFixed(1)}" stroke="#2A1A0C" stroke-width="6" stroke-linecap="round"/>
      <g class="hand">
        <line x1="${cx}" y1="${cy+r*.18}" x2="${cx}" y2="${cy-r+20}" stroke="#A8461F"
              stroke-width="3" stroke-linecap="round"/>
      </g>
      <circle cx="${cx}" cy="${cy}" r="7" fill="#2A1A0C"/>
      <circle cx="${cx}" cy="${cy}" r="3" fill="#A8461F"/>
      <circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="#000" stroke-width="6" opacity=".25"/>
    </g>`;
  },

  /* shot 8's five ticks. Stated, not dramatised. */
  ticks(svg, {from=2.0, step=.4}={}){
    svg.querySelectorAll(".tick").forEach((t,i)=>{
      const L = t.getTotalLength ? t.getTotalLength() : 120;
      t.style.strokeDasharray = L;
      t.style.setProperty("--dash", L);
      /* drawn, like a pen stroke — not faded in */
      EL.anim(t, "tickDraw", from+i*step, .32, "var(--e-expo)");
    });
  },

  /* shot 11's crowd. 94 lit amber, 6 red, seeded so the red six land
     in the same six places every render. */
  crowd(svg, {pop=5.0, step=.006, redAt=null}={}){
    const figs = [...svg.querySelectorAll(".fig")];
    const red  = new Set();
    const r = EL.rng(41);
    while(red.size < 6) red.add(Math.floor(r()*100));
    const split = redAt == null ? pop+1.6 : redAt;
    figs.forEach((f,i)=>{
      const isRed = red.has(i);
      /* phase 1: 94 light amber, the six stay unlit (dependence: almost everyone).
         phase 2: the six turn red, the 94 dim (addiction: fewer than 1 in 10).
         The old version lit the six red at the same moment as the 94, so both
         captions were illustrating one picture. */
      if (redAt == null){
        EL.animMulti(f, [
          {name:"fadeIn", dur:.3, delay:pop+i*step, ease:"linear"},
          {name: isRed ? "popInHard" : "figLit", dur: isRed?.42:.5, delay:split, ease:"var(--e-back)"}
        ]);
        f.querySelectorAll("rect,circle,path").forEach(s=>s.setAttribute("fill", isRed?"var(--accent)":"var(--q)"));
        return;
      }
      const list = [{name:"fadeIn", dur:.3, delay:pop+i*step, ease:"linear"}];
      if (!isRed) list.push({name:"figLit",   dur:.5, delay:pop+1.6+(i%10)*.02, ease:"var(--e-back)"},
                            {name:"figUnlit", dur:.6, delay:split, ease:"var(--e-soft)", fill:"forwards"});
      EL.animMulti(f, list);
      f.querySelectorAll("rect,circle,path").forEach(s=>s.setAttribute("fill", "var(--q)"));
      if (isRed){
        f.querySelectorAll("rect,circle,path").forEach(s=>s.setAttribute("fill", "#3A4250"));
        /* the red six arrive as their own layer ON TOP, so the 94 dimming
           cannot dim them too */
        const c = f.cloneNode(true);
        c.removeAttribute("class"); c.removeAttribute("style"); c.removeAttribute("data-i");
        c.setAttribute("opacity","1");
        c.querySelectorAll("rect,circle,path").forEach(s=>s.setAttribute("fill","#E8605B"));
        c.setAttribute("filter","url(#glowF)");
        EL.anim(c, "popInHard", split, .42, "var(--e-back)");
        c.style.transformBox = "fill-box"; c.style.transformOrigin = "50% 50%";
        svg.appendChild(c);
      }
    });
  },

};

/* =========================================================
   OVERLAY INJECTION
   ========================================================= */
if(stage){
  stage.insertAdjacentHTML("beforeend", `
    <svg id="grain" width="1080" height="1920" viewBox="0 0 1240 2080"
         preserveAspectRatio="none" aria-hidden="true">
      <g class="k" style="animation-name:grainShift;animation-duration:1.4s;
         animation-timing-function:steps(6,end);animation-iteration-count:infinite">
        <rect width="1240" height="2080" filter="url(#grainF)"/>
      </g>
    </svg>
    <div id="vig"></div>
    <div id="filmic"></div>
    <svg id="guides" width="1080" height="1920" viewBox="0 0 1080 1920" aria-hidden="true">
      <rect class="z-top"  x="0" y="0"    width="1080" height="180"/>
      <rect class="z-bot"  x="0" y="1600" width="1080" height="320"/>
      <rect class="z-rail" x="920" y="0" width="160" height="1920" opacity=".5"/>
      <rect class="z-band" x="110" y="180" width="860" height="1420"/>
      <text class="lbl-top"  x="24"  y="112">TOP UI — KEEP EMPTY</text>
      <text class="lbl-bot"  x="24"  y="1672">BOTTOM UI — KEEP EMPTY</text>
      <text class="lbl-rail" x="932" y="140">ACTION</text>
      <text class="lbl-rail" x="932" y="176">RAIL</text>
      <text class="lbl-band" x="126" y="1592">SAFE CONTENT BAND  110 → 970  ×  180 → 1600</text>
      <line class="tick" x1="110" y1="180"  x2="970"  y2="180"/>
      <line class="tick" x1="110" y1="1600" x2="970"  y2="1600"/>
      <line class="tick" x1="110" y1="180"  x2="110"  y2="1600"/>
      <line class="tick" x1="970" y1="180"  x2="970"  y2="1600"/>
    </svg>`);
}

/* Grain level is per shot (storyboard: Q 4->9%, the high drops to 2%, the
   floor has none). data-grain on <body> sets it; absent = the house default. */
if (stage && document.body.dataset.grain != null){
  const g = document.getElementById("grain");
  if (g) g.style.opacity = document.body.dataset.grain;
}

/* Procedural builders are OPT-IN. Auto-calling them here silently double-built
   anything a beat also constructed itself with its own timings. Each beat calls
   the builder it needs, with the timings that beat needs. */

/* =========================================================
   CLOCK
   ========================================================= */
let t=0, playing=false, raf=null, last=0, audio=null;

function render(v){
  t = v;
  if(fill) fill.style.width = (t/CFG.dur*100)+"%";
  if(tc)   tc.textContent = (t<10?"0":"") + t.toFixed(2);

  /* ONE clock. If a shot has been migrated to the GSAP engine, its timelines
     are scrubbed from here, so the animation and the scrub bar cannot disagree
     and scrubbing backwards is exact. Shots still on CSS keyframes ignore
     this — motion.js is only present on migrated shots. */
  if (window.M && M.seek) { try { M.seek(t, CFG.dur); } catch(e){} }
  else if (document.querySelector('script[src$="motion.js"]')) {
    /* motion.js is loaded but M is not reachable — the engine is dead and every
       tween in this shot is frozen. Surface it instead of rendering a still
       image that looks correct in any single frame. */
    if (!window.__motionWarned){ window.__motionWarned = 1;
      console.error('[] motion.js loaded but window.M is undefined — GSAP timelines will NOT play.'); }
  }

  /* The counter tween is owned by the beat that has the counter, via data
     attributes. It used to be hardcoded here at t=0.6-2.6s, which meant beat
     7 finished counting to 10 a full 1.4s BEFORE the word "ten" was spoken.
     Silent, because the number was right — just early. */
  const c = $("#counter");
  if(c && c.dataset.countTo){
    const from = +c.dataset.countStart, to = +c.dataset.countEnd, tgt = +c.dataset.countTo;
    const p = Math.max(0, Math.min(1, (t-from)/(to-from)));
    c.textContent = Math.round((1-Math.pow(1-p,3))*tgt);
  }
  if(nowBeat){
    let cur=null;
    for(const b of BEATS) if(t+CFG.offset >= b.t) cur=b;
    nowBeat.innerHTML = cur
      ? `▶ ${PARTLABEL} SHOT ${cur.n} &nbsp;${cur.name}<br>
         <span style="color:#39414F">global in ${(CFG.offset+t).toFixed(1)}s / ${TOTALOF}s</span>`
      : "&nbsp;";
  }
}

function loop(now){
  if(!playing) return;
  if(!last) last=now;
  const dt=(now-last)/1000; last=now;
  if(audio) return;
  render(Math.min(CFG.dur, t+dt));
  if(t>=CFG.dur){ stop(); return; }
  raf=requestAnimationFrame(loop);
}
function play(){
  if(t>=CFG.dur) restart();
  document.body.classList.add("playing");
  if(audio){ audio.currentTime=t; audio.play().catch(()=>{}); playing=true; }
  else { playing=true; last=0; raf=requestAnimationFrame(loop); }
  if($("#play")){ $("#play").innerHTML="&#10073;&#10073; PAUSE"; $("#play").classList.add("on"); }
}
function stop(){
  playing=false;
  document.body.classList.remove("playing");
  if(audio) audio.pause();
  if(raf) cancelAnimationFrame(raf);
  if($("#play")){ $("#play").innerHTML="&#9654; PLAY"; $("#play").classList.remove("on"); }
}
function restart(){
  document.body.classList.remove("playing");
  void stage.offsetWidth;
  if (window.M && M.reset) { try { M.reset(); } catch(e){} }
  render(0);
}
function replay(){ stop(); restart(); play(); }

if($("#play"))   $("#play").onclick   = ()=> playing?stop():play();
if($("#replay")) $("#replay").onclick = replay;
function toggleGuides(btn){
  const g = $("#guides");
  if(!g) return;
  const on = g.classList.toggle("on");
  if(btn) btn.classList.toggle("on", on);
}
if($("#bar")) $("#bar").onclick = e=>{
  const r=e.currentTarget.getBoundingClientRect();
  const v=Math.max(0,Math.min(CFG.dur,(e.clientX-r.left)/r.width*CFG.dur));
  const was=playing;
  stop(); restart(); render(v);
  if(audio) audio.currentTime=v;
  if(was) play();
};
addEventListener("keydown", e=>{
  if(e.code==="Space"){ e.preventDefault(); playing?stop():play(); }
  if(e.key==="g"||e.key==="G") $("#guide")&&$("#guide").click();
  if(e.key==="f"||e.key==="F"){
    document.fullscreenElement ? document.exitFullscreen()
      : document.documentElement.requestFullscreen();
  }
  if(e.key==="r"||e.key==="R") replay();
  if(e.key==="ArrowRight"){ stop(); restart(); render(Math.min(CFG.dur,t+1)); }
  if(e.key==="ArrowLeft"){  stop(); restart(); render(Math.max(0,t-1)); }
});
if($("#vo")) $("#vo").onchange = e=>{
  const f=e.target.files[0]; if(!f) return;
  if(audio){ audio.pause(); audio=null; }
  audio=new Audio(URL.createObjectURL(f));
  audio.addEventListener("ended",()=>{ stop(); render(CFG.dur); });
  if(playing){ audio.currentTime=t; audio.play().catch(()=>{}); }
  const sub=$("#ui .sub");
  if(sub) sub.textContent=`${PARTLABEL} · shot ${CFG.beat||"full"} · SYNCED TO ${f.name.replace(/\.[^.]+$/,"")}`;
};

/* beat rail */
if($("#beatMarks")){
  const m=$("#beatMarks"), l=$("#beatList");
  BEATS.forEach(b=>{
    const i=document.createElement("i"); i.style.left=(b.t/TOTALOF*100)+"%"; m.appendChild(i);
    const n=document.createElement("b"); n.style.left=(b.t/TOTALOF*100)+"%"; n.textContent=b.n; m.appendChild(n);
    const row=document.createElement("div");
    row.innerHTML=`<span>${String(b.t).padStart(2,"0")}s</span> · ${b.name}`;
    l.appendChild(row);
  });
  setInterval(()=>{
    $$("#beatList div").forEach(d=>d.style.color="#464E5D");
    for(const b of BEATS) if(CFG.offset+t>=b.t){
      const el=$$("#beatList div")[b.n-1]; if(el) el.style.color="var(--signal)";
    }
  },120);
}

function fit(){
  const s=Math.min(1,(innerHeight-80)/1920,(innerWidth*0.55)/1080);
  stage.style.transform=`scale(${s})`;
  $("#wrap").style.width=1080*s+"px";
  $("#wrap").style.height=1920*s+"px";
}
addEventListener("resize",fit); fit();

render(0);
